import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '../globals.css'
import UserLayout from '@/ui/Layout/UserLayout'
import { Providers } from '@/utills/providers'
import { ToastContainer } from 'react-toastify'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Globe.com',
    description: 'Generated by Next js',
}

export default function AccountLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${montserrat.className} body-color`}>
                <Providers>
                    <UserLayout>
                        {children}
                    </UserLayout>
                </Providers>
                <ToastContainer />
            </body>
        </html>
    )
}